// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Remapper.Test.DataAccess;

namespace Remapper.Test.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    partial class ContentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Remapper.Test.DataAccess.BlogPostDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasMaxLength(65000);

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("BlogPostDTOs");
                });

            modelBuilder.Entity("Remapper.Test.DataAccess.ContentItemDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("ContentItemDTOs");
                });

            modelBuilder.Entity("Remapper.Test.DataAccess.ProductReviewDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Review")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2000);

                    b.HasKey("Id");

                    b.ToTable("ProductReviewDTOs");
                });

            modelBuilder.Entity("Remapper.Test.DataAccess.BlogPostDTO", b =>
                {
                    b.HasOne("Remapper.Test.DataAccess.ContentItemDTO", "ContentItem")
                        .WithOne("BlogPost")
                        .HasForeignKey("Remapper.Test.DataAccess.BlogPostDTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Remapper.Test.DataAccess.ProductReviewDTO", b =>
                {
                    b.HasOne("Remapper.Test.DataAccess.ContentItemDTO", "ContentItem")
                        .WithOne("ProductReview")
                        .HasForeignKey("Remapper.Test.DataAccess.ProductReviewDTO", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
